version: '3.8'
services:
  legion-auth:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - legion-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  legion-data: